### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dimaunx2** [mcn-org/prow-test#29]
/assign @dimaunx 
/kind support

**Comment by dimaunx2** [comment]
help

**Comment by dimaunx2** [comment]
help wanted

**Comment by dimaunx1** [comment]
@dimaunx2: 
	This request has been marked as needing help from a contributor.

Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/guide/help-wanted.md).

If this request no longer meets these requirements, the label can be removed
by commenting with the `/remove-help` command.


<details>

In response to [this](https://github.com/mcn-org/prow-test/issues/29):

>/help


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by dimaunx1** [comment]
@dimaunx2: Closing this issue.

<details>

In response to [this](https://github.com/mcn-org/prow-test/issues/29#issuecomment-495238927):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
